accounts/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView, LoginView
from django.urls import path, re_path, include
from django.views.generic import RedirectView

# from accounts import views
from .views import *
from . import views

# from accounts.views import SignUpAutoComplete

app_name = 'accounts'

urlpatterns = [
    path('profile/<str:pk>/', profile_detail, name='profile_detail'),
    path('login-form/', login_view_modal, name='login_view_modal'),
    path('login/', user_login, name='user_login'),
    # path('signup/', user_signup, name='user_signup'),
    path('change-profile/', change_profile, name='change_profile'),

]

shop/urls.py
from django.urls import path, re_path

from .views import *

app_name='shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('add-to-cart/<pk>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove_from_cart'),
	path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce_quantity_item'),
    # path("callback/", callback, name="callback"),
    # path('order-summary/', order_summary, name='order_summary'),
    # path('order/', order, name='order'),
    # path('payment/<payment_option>/', payment, name='payment'),
    # path('paymenthandler/', paymenthandler, name='paymenthandler'),
    # path('', FacetedSearchView.as_view(), name='haystack_search'),
    # path('find/', FacetedSearchView.as_view(), name='haystack_search'),
    # path('product/(?P<slug>[\w-]+)/$', ProductView.as_view(), name='product'),
    # path('search/autocomplete/$', autocomplete),
]

shrinivasdiagnostics/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

from shop.views import *
from order.views import *
from accounts.views import *

from djoser import views as djoser_views
# from rest_framework_jwt import views as jwt_views

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('admin/', include('massadmin.urls')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('accounts.urls')),

    path('book-test/', include('shop.urls')),
    path('package-description/<pk>/', product_detail, name='product_detail'),
    path('shopping-cart/', shopping_cart, name='shopping_cart'),
    # path('order/', order, name='order'),
    path('checkout/', include('order.urls')),
    path('checkout/', include('address.urls')),
    # path("callback/", callback, name="callback"),
	# path('payment/', paymenthandler, name='paymenthandler'),
    # path("payment/", order_payment, name="order_payment"),
    path('my-orders/', my_orders, name='my_orders'),

    path('search/', include('haystack.urls')),
    path('book-test/autocomplete/', productlist_search, name='productlist_search'),
    # path('search/autocomplete/', productlist_search(view_class=SearchView, template='index.html', form_class=ProductSearchForm), name='haystack_search'),

    path('api/', include('djoser.urls')),
    path('api/', include('djoser.urls.jwt')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import get_user_model

from .managers import UserManager

from shop.models import *

from phonenumber_field.modelfields import PhoneNumberField
# from cities_light.models import *

GENDER_CHOICES = (
	("male", _('Male')),
	("female", _('Female')),
	# ("unknown", _('Unknown'))
)

RELATION_CHOICES = (
	("father", _('Father')),
	("mother", _('Mother')),
	("spouse", _('Spouse')),
	("son", _('Son')),
	("daughter", _('Daughter')),
	("family", _('Family'))
)

# Create your models here.
class Profile(AbstractBaseUser, PermissionsMixin):
	full_name = models.CharField(max_length=255, null=True, blank=True)
	username = models.CharField(max_length=255, blank=True, null=True)
	email = models.EmailField(verbose_name='Email', error_messages={'unique':"This email has already been registered.",}, max_length=255, unique=True)
	phone_number = PhoneNumberField(null=True, blank=False)
	phone_verified = models.BooleanField(default=False)
	birth_date = models.DateField(null=True, blank=True)
	gender = models.CharField(max_length=255, choices=GENDER_CHOICES, default=None, blank=True, null=True)

	is_active = models.BooleanField(default=True, blank=True, null=True)
	is_staff = models.BooleanField(default=False)
	is_admin = models.BooleanField(default=False)
	is_superuser = models.BooleanField(default=False)

	objects = UserManager()
	# EMAIL_FIELD = "email"
	USERNAME_FIELD = "email"
	REQUIRED_FIELDS = ["phone_number"]

	class Meta:
		verbose_name = _('Profile')
		verbose_name_plural = _("Profile")

	def __str__(self):
		return self.email

	def clean(self):
	  super().clean()
	  self.email = self.__class__.objects.normalize_email(self.email)

	def clean_title(self):
		return self.cleaned_data['full_name'].capitalize()


	# def get_display_name(self):
	#   if self.full_name != '':
	#       return self.full_name
	#   else:
	#       return self.username

	# def get_name(self):
	#   full_name = '%s %s' % (self.first_name, self.last_name)
	#   return full_name.strip()
	#   # return self.email

	# def get_short_name(self):
	#   return self.first_name
		# return self.email

	# def email_user(self, subject, message, from_email=None, **kwargs):
	# 	send_mail(subject, message, from_email, [self.email], **kwargs)

	# def verify_email(self):
	#   if self.email_verified is False:
	#       secret = uuid.uuid4().hex[:20]
	#       self.email_secret = secret
	#       html_message = render_to_string("email/verify_email.html", {"secret": secret})
	#       send_mail("Verify Hairbnb Account", strip_tags(html_message), settings.EMAIL_FROM, [self.email], html_message=html_message,)
	#       self.save()
	#   return


class Patient(models.Model):
	full_name = models.CharField(max_length=255, null=True, blank=True)
	email = models.EmailField(verbose_name='Email', error_messages={'unique':"This email has already been registered.",}, max_length=255, unique=True)
	phone_number = PhoneNumberField(null=True, blank=True)
	birth_date = models.DateField(null=True, blank=True)
	gender = models.CharField(max_length=255, choices=GENDER_CHOICES, default=None, blank=True, null=True)
	relation = models.CharField(max_length=255, choices=RELATION_CHOICES, default=None, blank=True, null=True)
	user_patient = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=False, related_name='user_patient')
	test_package = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True, related_name='test_patient')

	class Meta:
		verbose_name = _('Patient')
		verbose_name_plural = _("Patient")

	def __str__(self):
		return self.full_name
	

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import ModelForm, HiddenInput
from django.http import Http404
from django.utils.translation import gettext_lazy as _

from allauth.account.forms import LoginForm, SignupForm
# from bootstrap_datepicker_plus import *
from bootstrap_modal_forms.forms import *
# from bootstrap_modal_forms.mixins import *
# from cities_light.models import *
# from crispy_forms.bootstrap import *
# from crispy_forms.helper import *
# from crispy_forms.layout import *
# from captcha.fields import ReCaptchaField
# from captcha.widgets import ReCaptchaV2Checkbox, ReCaptchaBase, ReCaptchaV3


from datetime import datetime, date

from .models import *
from address.models import *

# from .lookups import *
# from subscription.models import *

# from easy_select2 import *


def get_today():
    return date.today().strftime('%d-%m-%Y')

# class MyLoginForm(BSModalModelForm):
class MyLoginForm(AuthenticationForm):
# class MyLoginForm(PopRequestMixin, CreateUpdateAjaxMixin, UserCreationForm):
    class Meta:
        model = Profile
        # model = User
        fields = ['phone_number']
        # fields = '__all__'
        
    phone_number = forms.CharField(required=False, label="", widget=forms.TextInput(attrs={'class': "form-control"}))

class MySignUpForm(SignupForm):

    full_name = forms.CharField(max_length=100, required=False, label=_('Full Name:'), widget=forms.TextInput(attrs={'class': "form-control"}))
    email = forms.EmailField(required=False, label='', widget=forms.TextInput(attrs={'class': "form-control"}))

    def save(self, request):
        user = super().save(request)
        user.full_name = self.cleaned_data['full_name']
        user.email = self.cleaned_data['email']
        user.is_active = True
        user.is_admin = False
        user.save()
        return user

class ChangeUserProfile(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    full_name = forms.CharField(max_length=100, required=True, label='', widget=forms.TextInput(attrs={'class': "form-control"}))
    email = forms.EmailField(required=False, label='', widget=forms.TextInput(attrs={'class': "form-control"}))

    class Meta:
        model = Profile
        fields = ('full_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        # widgets = {
        #     'phone_verified': forms.HiddenInput(),
        # }

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
        # self.helper = FormHelper()
        # self.helper.layout = Layout(
        #     Div(InlineRadios('')),
        # )

    # full_name = forms.CharField(required=False, label="", widget=forms.TextInput(attrs={'class': "form-control"}))
    # username = forms.CharField(required=False, label="", widget=forms.HiddenInput(attrs={'class': "form-control"}))
    # is_patient = forms.BooleanField(required=False, label='', widget=forms.HiddenInput())
    # is_active = forms.BooleanField(required=False, label='', widget=forms.HiddenInput())
    # email = forms.EmailField(required=False, label="", widget=forms.HiddenInput(attrs={'class': "form-control"}))
    # password = forms.CharField(required=False, label="", widget=forms.HiddenInput(attrs={'class': "form-control"}))
    # address = forms.CharField(required=False, label="", widget=forms.Textarea(attrs={'class': "form-control", 'rows': 4, 'cols': 15}))

class PatientForm(forms.Form):
    full_name = forms.CharField(required=False, label="", widget=forms.TextInput(attrs={'class': "form-control"}))
    email = forms.EmailField(required=False, label="", widget=forms.HiddenInput(attrs={'class': "form-control"}))
    phone_number = forms.CharField(required=False, label="", widget=forms.TextInput(attrs={'class': "form-control"}))


class ChangeUserAddress(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    user = forms.CharField(max_length=100, required=True, label='', widget=forms.TextInput(attrs={'class': "form-control"}))
    address = forms.EmailField(required=False, label='', widget=forms.TextInput(attrs={'class': "form-control"}))

    class Meta:
        model = Address
        fields = ('user', 'address')

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.views import LogoutView, LoginView, PasswordChangeView
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *
from order.models import *

from bootstrap_modal_forms.generic import BSModalLoginView

# Create your views here.
def user_login(request):
	username = password = ''
	response_data = {}
	is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

	if request.POST and request.is_ajax:
		phone = request.POST['phone']
		password = request.POST['password']

		try:
			get_user_by_phone = UserAccount.objects.get(phone=phone)
			user_phone = get_user_by_phone.phone
			username = get_user_by_phone.user.get_username()
			get_user = User.objects.get(username=username)

			if get_user.check_password(password):
				user = authenticate(username=username, password=password)
				if user is not None:
					if user.is_active:
						login(request, user)
						response_data = {'login' : "Success"}
					else:
						url = "http://2factor.in/API/V1/"+API_KEY+"/SMS/" + user_phone + "/AUTOGEN/OTPSEND"
						payload = ""
						response = requests.request("GET", url, data=payload)
						otp_data = response.json()
						response_data['user'] = "not active"
						response_data['user_phone'] = user_phone
				else:
					response_data = {'user':"password wrong"}
		except UserAccount.DoesNotExist:
			# except ObjectDoesNotExist:
			response_data = {'user':"nouser"}
	else:
		username = password = ''
		response_data = {'login': "Failed"}
	return HttpResponse(JsonResponse(response_data))


# @receiver(user_logged_in)
# class MyLoginView(BSModalUpdateView):
# class MyLoginView(LoginView):
class MyLoginView(BSModalLoginView):
	template_name = 'accounts/login_modal.html'
	authentication_form = MyLoginForm
	form_class = MyLoginForm
	success_message = 'Success: You were successfully logged in.'
	success_url = reverse_lazy('core:homepage')
	extra_context = dict(success_url=reverse_lazy('core:homepage'))
	# next = request.POST.get('next', '/')
	# return HttpResponseRedirect(next)

#   # def get_form_kwargs(self):
#   #   kwargs = super().get_form_kwargs()
#   #   kwargs['request'] = self.request
#   #   return kwargs


login_view_modal = MyLoginView.as_view()


def profile_detail(request, pk):
	page_title = _('Account Profile')
	user_id = Profile.objects.get(email=request.user)
	full_name = user_id.full_name
	phone_number = user_id.phone_number
	email = user_id.email
	user_address = Address.objects.filter(user=user_id)
	user_order = Order.objects.filter(user=user_id, item_order=False).count()

	initial_dict = {
		# 'full_name': get_fullname,
		# 'birth_date': get_nataldate,
		# 'birth_city': get_birth_city,
		# 'longitude': get_city_longitude,
		# 'latitude': get_city_latitude,
		# 'member': memberlist,
	}

	if request.method == "POST":
		form = ProfileForm(request.POST or None)

		get_city_name = cache.get('get_city_name')
		get_city_longitude = cache.get('get_city_longitude')
		get_city_latitude = cache.get('get_city_latitude')

		if form.is_valid():

			profile = form.save(commit=False)
			# profile.full_name = form.cleaned_data['full_name']
			profile.full_name = form.cleaned_data.get('full_name')
			# profile.birth_city = form.cleaned_data['birth_city']
			profile.birth_city = form.cleaned_data.get('birth_city')
			# profile.birth_date = form.cleaned_data['birth_date']
			profile.birth_date = form.cleaned_data.get('birth_date')
			profile.save()
			messages.warning(request, form.errors)

		else:
			messages.warning(request, form.errors)
	else:
		form = ProfileForm(initial=initial_dict, instance=request.user)

	context = {
		'page_title': page_title,
		'form': form,
		'full_name': full_name,
		'phone_number': phone_number,
		'email': email,
		'user_address': user_address,
		'user_id': user_id,
		'user_order': user_order,
	}

	return render(request, 'accounts/myprofile.html', context)


@login_required
def change_profile(request):
	user_id = Profile.objects.get(email=request.user)
	page_title = _('Change Profile')
	form = ChangeUserProfile(prefix='profile')

	if request.method == 'POST':
		form = ChangeUserProfile(request.POST or None, instance=request.user)

		if form.is_valid():
			profile = form.save(commit=False)
			profile.full_name = form.cleaned_data['full_name']
			profile.email = form.cleaned_data['email']
			profile.ic_number = form.cleaned_data['ic_number']
			profile.save()

			messages.success(request, _('Your profile has been change successfully.'))
			return HttpResponseRedirect('/accounts/')
		else:
			messages.warning(request, form.errors)

	else:
		form = ChangeUserProfile(instance=request.user)

	context = {
		'user_id': user_id,
		'page_title': page_title,
		'form': form,
	}

	return render(request, 'accounts/change.html', context)

templates/accounts/account_inactive.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Account Inactive" %}{% endblock %}

{% block content %}
<h1>{% trans "Account Inactive" %}</h1>

<p>{% trans "This account is inactive." %}</p>
{% endblock %}

templates/accounts/change.html
{% extends 'base.html' %}

{% load account %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block style %}
<link href="{% static 'css/account.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block headtitle %}
    {{ page_title }} | {{ titles.title }}
{% endblock %}

{% block content %}

<div class="row isi dataaccount">
    <div class="col-12">

        <div class="row">
            <div class="col-12">
                <h4>{% trans "Change Profile" %}</h4>
                <hr>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <form method="post">
                {% csrf_token %}

                    <div class="form-group row">
                        <label for="lastname" class="col-4 col-form-label">{% trans "Full Name*" %}</label>
                        <div class="col-6">
                            {{ form.full_name|as_crispy_field }}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-4 col-form-label">{% trans "Email*" %}</label>
                        <div class="col-6">
                            {{ form.email|as_crispy_field }}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="ic_number" class="col-4 col-form-label">{% trans "IC Number" %}</label>
                        <div class="col-6">
                        </div>
                    </div>

                    <button class="btn btn-primary" type="submit" name="action">{% trans "Change Profile" %}</button>
                    <a class="btn btn-danger" href="{{ login_url }}">{% trans "Cancel" %}</a>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/accounts/email.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "E-mail Addresses" %}{% endblock %}

{% block content %}
    <h1>{% trans "E-mail Addresses" %}</h1>
{% if user.emailaddress_set.all %}
<p>{% trans 'The following e-mail addresses are associated with your account:' %}</p>

<form action="{% url 'account_email' %}" class="email_list" method="post">
{% csrf_token %}
<fieldset class="blockLabels">

  {% for emailaddress in user.emailaddress_set.all %}
<div class="ctrlHolder">
      <label for="email_radio_{{forloop.counter}}" class="{% if emailaddress.primary %}primary_email{%endif%}">

      <input id="email_radio_{{forloop.counter}}" type="radio" name="email" {% if emailaddress.primary or user.emailaddress_set.count == 1 %}checked="checked"{%endif %} value="{{emailaddress.email}}"/>

{{ emailaddress.email }}
    {% if emailaddress.verified %}
    <span class="verified">{% trans "Verified" %}</span>
    {% else %}
    <span class="unverified">{% trans "Unverified" %}</span>
    {% endif %}
      {% if emailaddress.primary %}<span class="primary">{% trans "Primary" %}</span>{% endif %}
</label>
</div>
  {% endfor %}

<div class="buttonHolder">
      <button class="secondaryAction" type="submit" name="action_primary" >{% trans 'Make Primary' %}</button>
      <button class="secondaryAction" type="submit" name="action_send" >{% trans 'Re-send Verification' %}</button>
      <button class="primaryAction" type="submit" name="action_remove" >{% trans 'Remove' %}</button>
</div>

</fieldset>
</form>

{% else %}
<p><strong>{% trans 'Warning:'%}</strong> {% trans "You currently do not have any e-mail address set up. You should really add an e-mail address so you can receive notifications, reset your password, etc." %}</p>

{% endif %}

  {% if can_add_email %}
    <h2>{% trans "Add E-mail Address" %}</h2>

    <form method="post" action="{% url 'account_email' %}" class="add_email">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="action_add" type="submit">{% trans "Add E-mail" %}</button>
    </form>
  {% endif %}

{% endblock %}


{% block extra_body %}
<script type="text/javascript">
(function() {
  var message = "{% trans 'Do you really want to remove the selected e-mail address?' %}";
  var actions = document.getElementsByName('action_remove');
  if (actions.length) {
    actions[0].addEventListener("click", function(e) {
      if (! confirm(message)) {
        e.preventDefault();
      }
    });
  }
})();
</script>
{% endblock %}

templates/accounts/email_confirm.html
{% extends "base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Confirm E-mail Address" %}{% endblock %}


{% block content %}
<h1>{% trans "Confirm E-mail Address" %}</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
{% csrf_token %}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

{% endif %}

{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load account socialaccount %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block extra_style %}
<link href="{% static 'css/based.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/desktop.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-3 col-md-3 col-sm-12">
		</div>
		<div class="col-lg-6 col-md-6 col-sm-12">
			<h1>{% trans "Sign In" %}</h1>

			{% get_providers as socialaccount_providers %}
			{% if socialaccount_providers %}

			<p>{% blocktrans with site.name as site_name %}Please sign in with one
			of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
			for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

			<div class="socialaccount_ballot">
				<ul class="socialaccount_providers">
					{% include "socialaccount/snippets/provider_list.html" with process="login" %}
				</ul>

				<div class="login-or">{% trans 'or' %}</div>
			</div>


			{% include "socialaccount/snippets/login_extra.html" %}
			{% else %}

			<p>{% blocktrans %}If you have not created an account yet, then please <a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
			{% endif %}

			<form class="login" method="POST" action="{% url 'account_login' %}">
			{% csrf_token %}

				{{ form.as_p }}
				{% if redirect_field_value %}
				<input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
				{% endif %}
				<a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
				<button class="primaryAction" type="submit">{% trans "Sign In" %}</button>
			</form>
		</div>

		<div class="col-lg-3 col-md-3 col-sm-12">
		</div>
	</div>
</div>
{% endblock %}

templates/accounts/myorder.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block extra_style %}
{% endblock %}


{% block content %}

<section class="profile_section">
    <div class="container">
        <h2 class="home_title">Account Profile</h2>
        <div class="marketplace-wrapper">
            <div class="left-filter">
                <div class="left_menu">
                    <ul>
                        <li><a class="active" href="{% url 'my_orders' %}">Orders</a></li>
                        <li><a class="" href="{% url 'accounts:profile_detail' user_id.pk %}">Profile</a></li>
                        {# <li><a class="" href="download-report.html">Download Report</a></li> #}
                    </ul>
                </div>
            </div>
            <div class="right-cont">
                <div class="profile_box add_box">
                    <a href="#">Place Your Frist Order</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

{% block extra_jscript %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script type='text/javascript'>
$(document).ready(function()
{
    $(document).on('click', '.number-spinner button', function () {
        var btn = $(this),
            oldValue = btn.closest('.number-spinner').find('input').val().trim(),
            newVal = 0;

        if (btn.attr('data-dir') == 'up') {
            newVal = parseInt(oldValue) + 1;
        } else {
            if (oldValue > 1) {
                newVal = parseInt(oldValue) - 1;
            } else {
                newVal = 1;
            }
        }
        btn.closest('.number-spinner').find('input').val(newVal);
    });

});
</script>

{% endblock %}

templates/accounts/password_change.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>

    <form method="POST" action="{% url 'account_change_password' %}" class="password_change">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="action">{% trans "Change Password" %}</button>
        <a href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
    </form>
{% endblock %}

templates/accounts/password_reset.html
{% extends "base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}

    <h1>{% trans "Password Reset" %}</h1>
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}

    <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it." %}</p>

    <form method="POST" action="{% url 'account_reset_password' %}" class="password_reset">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Reset My Password' %}" />
    </form>

    <p>{% blocktrans %}Please contact us if you have any trouble resetting your password.{% endblocktrans %}</p>
{% endblock %}

templates/accounts/password_reset_from_key_done.html
{% extends "base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>
    <p>{% trans 'Your password is now changed.' %}</p>
{% endblock %}

templates/accounts/signup_closed.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Up Closed" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Up Closed" %}</h1>

<p>{% trans "We are sorry, but the sign up is currently closed." %}</p>
{% endblock %}