homepage/urls.py
from django.urls import path

from .views import *

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
]

shop/urls.py
from django.urls import path, re_path

from .views import *

app_name='shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('add-to-cart/<pk>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove_from_cart'),
	path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce_quantity_item'),
    # path("callback/", callback, name="callback"),
    # path('order-summary/', order_summary, name='order_summary'),
    # path('order/', order, name='order'),
    # path('payment/<payment_option>/', payment, name='payment'),
    # path('paymenthandler/', paymenthandler, name='paymenthandler'),
    # path('', FacetedSearchView.as_view(), name='haystack_search'),
    # path('find/', FacetedSearchView.as_view(), name='haystack_search'),
    # path('product/(?P<slug>[\w-]+)/$', ProductView.as_view(), name='product'),
    # path('search/autocomplete/$', autocomplete),
]

shrinivasdiagnostics/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

from shop.views import *
from order.views import *
from accounts.views import *

from djoser import views as djoser_views
# from rest_framework_jwt import views as jwt_views

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('admin/', include('massadmin.urls')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('accounts.urls')),

    path('book-test/', include('shop.urls')),
    path('package-description/<pk>/', product_detail, name='product_detail'),
    path('shopping-cart/', shopping_cart, name='shopping_cart'),
    # path('order/', order, name='order'),
    path('checkout/', include('order.urls')),
    path('checkout/', include('address.urls')),
    # path("callback/", callback, name="callback"),
	# path('payment/', paymenthandler, name='paymenthandler'),
    # path("payment/", order_payment, name="order_payment"),
    path('my-orders/', my_orders, name='my_orders'),

    path('search/', include('haystack.urls')),
    path('book-test/autocomplete/', productlist_search, name='productlist_search'),
    # path('search/autocomplete/', productlist_search(view_class=SearchView, template='index.html', form_class=ProductSearchForm), name='haystack_search'),

    path('api/', include('djoser.urls')),
    path('api/', include('djoser.urls.jwt')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import widgets
from django.shortcuts import render
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
# from django.contrib.postgres.fields.jsonb import JSONField

from shop.models import *
from .models import *

from crispy_forms.bootstrap import *
from crispy_forms.helper import *
from crispy_forms.layout import *
# from selectable.forms import *
# from selectable_select2.widgets import *
# from phonenumber_field.formfields import *
from phonenumber_field.widgets import *
# from django_select2 import forms as s2forms
# from django_select2.forms import *

import datetime

# class ProductWidget(s2forms.Select2Widget):
#     search_fields = [
#         "title__icontains",
#     ]

class ProductForm(forms.Form):
    # autocomplete = forms.CharField(
    #     label = '',
    #     widget = AutoCompleteWidget(ProductLookup),
    #     required = False,
    # )
    # product_title = AutoCompleteSelectField(lookup_class=ProductLookup, label='Select a fruit')
    # product_title = forms.CharField(widget=ProductWidget)
    # product_title = forms.CharField(widget=ModelSelect2Widget(model=Product, search_fields=['title__icontains'])
    product_title = forms.CharField(required=False, widget=forms.TextInput())
    # product_title = AutoCompleteWidget(ProductLookup, placeholder='select related item')
    # product_title = forms.ModelChoiceField(queryset=Product.objects.all().order_by('title'), widget=Select2())
    # product_title = forms.ModelChoiceField(required=True, label="", queryset=Product.objects.all().order_by('title'), widget=Select2(attrs={'class': "form-control"}))

# class ProductForm(forms.ModelForm):
    # Meta = select2_modelform_meta(Product)

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.helper = FormHelper()
    #     self.helper.layout = Layout(Div(InlineRadios('')),)

    # class Meta:
    #     model = Product
    #     fields = ('title',)
    #     widgets = {
    #         "title": ProductWidget,
    #         # 'title' : AutoCompleteSelect2Widget(ProductLookup, placeholder='Search for a test, health package or Labs')
    #     }

    # metadata = JSONField()
    # product_title = forms.ModelChoiceField(required=True, label="", queryset=Product.objects.all().order_by('title'), widget=Select2(attrs={'class': "search-container"}))
    # product_title = forms.ModelChoiceField(label="", queryset=Product.objects.distinct('scenarioAreaName'), empty_label="Placeholder")

    # product_title = AutoCompleteSelectField('productlookup', required=False, help_text=None)
    # product_title = AutoCompleteSelectMultipleField('title', required=False, help_text=None)

homepage/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.views import LogoutView, LoginView, PasswordChangeView
from django.http import HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from .models import *
from .forms import *

from accounts.models import *
from shop.models import *
from shop.forms import *
from order.models import *
from schedule.forms import *

from haystack.generic_views import FacetedSearchView as BaseFacetedSearchView, SearchView
from haystack.query import SearchQuerySet

# Create your views here.
def index(request):
	is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
	page_title = _('Check the Best Blood Test &amp; Pathology Lab in India with Shrinivas Diagnostics Labs')
	user_id = request.user.is_authenticated
	user_order = Order.objects.filter(user=user_id, item_order=False).count()
	products = Product.objects.filter(available=True)
	categories = Category.objects.all()
	# user_profile = Profile.objects.filter(id=user_id).values_list('id', True)
	if user_id:
		user_profile = Profile.objects.get(email=request.user)
		userprofile = user_profile.id
	else:
		pass

	initial_dict = {
		# 'ticker_code': get_ticker_id,
	}

	aforms = ProductForm()
	bforms = ScheduleForm()

	if request.method == "POST":
		aforms = ProductForm(request.POST or None)
		bforms = ScheduleForm(request.POST or None)

		# if aforms.is_valid() and bforms.is_valid():
		if bforms.is_valid():
			# products = Schedule()
			# # products.title = aforms.cleaned_data['title']
			# products.title = aforms.cleaned_data['title']
			# # products = aforms.cleaned_data['duration_time_from']
			# products.phone_number = aforms.cleaned_data['phone_number']
			# products.city = aforms.cleaned_data['city']
			# # products = Schedule()
			# products.save()

			schedule = Schedule()
			schedule.full_name = bforms.cleaned_data['full_name']
			schedule.phone_number = bforms.cleaned_data['phone_number']
			schedule.city = bforms.cleaned_data['city']
			schedule.save()

			# messages.success(request, 'aforms was created.')
			messages.success(request, 'Your Home Collection Schedule was created.')
			return redirect('homepage:index')
		else:
			# messages.warning(request, aforms.errors)
			messages.warning(request, bforms.errors)
	else:
		# aforms = ProductForm(initial=initial_dict)
		# bforms = ScheduleForm(initial=initial_dict)

		context = {
			'page_title': page_title,
			'user_order': user_order,
			'products': products,
			'aforms': aforms,
			'bforms': bforms,
			'categories': categories,
		}
		return render(request, 'homepage/home.html', context)

	context = {
		'page_title': page_title,
		'user_order': user_order,
		'products': products,
		'aforms': aforms,
		'bforms': bforms,
		'categories': categories,
		'user_profile': userprofile,
	}
	return render(request, 'homepage/home.html', context)

def productlist_search(request):
	sqs = None

	if request.method == "GET":
		if "q" in request.GET:
			query = str(request.GET.get("q"))
			search_models = []
			search_models = [Product]
			sqs = SearchQuerySet().all().filter(q=query).models(*search_models)

			context = {
				'sqs': sqs,
			}
	return render(request, "shop/product_list.html", context)

templates/homepage/health_packages.html
<!-- Health Packages section start-->
<section class="home_section">
	<div class="container">
		<h2 class="home_title">Popular Health Packages</h2>
		<div id="list-slider" class="owl-carousel owl-theme list_slider">

			{% for item in products %}
			<div class="item">
				<div class="listing_box">
					<div class="listing_header">
						<div class="best_seller">Best Seller</div>
						<h3><a class="product_detail" href="{{ item.get_absolute_url }}" title="{{ item.title }}">{{ item.title }}</a></h3>
						<p>₹{{ item.discount_price }}<span>₹{{ item.price }}</span></p>

						<div class="testes_tag">Tests</div>
						<form action="{% url 'shop:add_to_cart' item.pk %}" method="POST">
						{% csrf_token %}
							<a href="{% url 'shop:add_to_cart' item.pk %}" class="add_cart">Add to Cart</a>
						</form>
					</div>
					<div class="listing_body custom_scroll">
						<p class="l_title">{{ item.category }}</p>
						<p class="l_text">{{ item.prerequisites }}</p>
						<p class="l_text">{{ item.samplecutoff }}</p>
						<p class="l_text">{{ item.report }}</p>
						<p class="l_title">{{ item.category }}</p>
						<p class="l_text">{{ item.speciment }}</p>
						<p class="l_text">{{ item.method }}</p>
						<p class="l_title">{{ item.category }}</p>
						<p class="l_text">{{ item.quantitytemperature }}</p>
						<p class="l_text">{{ item.quantitytemperature }}</p>
					</div>
				</div>
			</div>
			{% endfor %}

		</div>
	</div>
</section><!-- Health Packages section end-->

templates/homepage/hero.html
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

<!-- hero section start -->
<div class="banner_area">
	<div class="form_area">
		<div class="form_box">
			<h2>Schedule a Home Collection</h2>
			<p>Choose from a range of comprehensive tests and packages and book home collection from the comfort of your home.</p>
			<form action="" method="POST" class="webform-submission-form" id="webform-submission-form">
			{% csrf_token %}
				<div class="mb-3">
					{% render_field bforms.full_name|add_class:"form-control required" type="text" placeholder="What is your name?*" %}
				</div>
				<div class="mb-3">
					{% render_field bforms.phone_number|add_class:"form-control required" type="text" placeholder="Mobile number*" %}
				</div>
				<div class="mb-3">
					{% render_field bforms.city|add_class:"form-control required" type="text" placeholder="Address*" %}
				</div>
				<button class="btn_submit">Submit</button>
			</form>
		</div>
	</div>

	<div class="slider_area">
		<div id="home-slider" class="owl-carousel owl-theme">
			<div class="item">
				<img src="assets/images/images/slide1.png" alt="">
			</div>
			<div class="item">
				<img src="assets/images/images/slide2.png" alt="">
			</div>
			<div class="item">
				<img src="assets/images/images/slide3.png" alt="">
			</div>
		</div>
	</div>
</div>
<!-- hero section end -->

templates/homepage/hero_schedule.html
<!-- hero section start -->
<section class="hero">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-6 col-md-12 col-sm-12 schedule-home-collection">
				<div class="schedule-home-card"  data-aos="fade-right" data-aos-duration="1000">
					<div class="region region-schedule-home-collection">
						<div id="block-webform-5" class="block block-webform block-webform-block">
							<form action="/" method="POST" class="webform-submission-form webform-submission-add-form webform-submission-schedule-a-home-collection-form webform-submission-schedule-a-home-collection-add-form js-webform-disable-autosubmit js-webform-details-toggle webform-details-toggle" id="webform-submission-schedule-a-home-collection-add-form">
								<h3>Please fill OTP</h3>
								<p>We have just sent you an OTP on<span class="example-number">8968306095</span></p>
								<div data-webform-key="please_fill_otp" id="edit-please-fill-otp" class="js-form-wrapper form-wrapper">
									<div id="otp1_table">
										<div id="edit-otp1" class="js-form-item form-item js-form-type-webform-multiple form-type-webform-multiple js-form-item-otp1 form-item-otp1 form-no-label">
											<div class="webform-multiple-table webform-multiple-table-responsive">
												<table id="edit-otp1-items" class="responsive-enabled" data-striping="1">
													<thead>
														<tr>
															<th colspan="1"><span class="visually-hidden">OTP1</span></th>
														</tr>
													</thead>
													<tbody>
														<tr class="odd">
															<td>
																<div class="js-form-item form-item js-form-type-textfield form-type-textfield js-form-item-otp1-items-0--item- form-item-otp1-items-0--item- form-no-label">
																	<label for="edit-otp1-items-0-item-" class="visually-hidden">OTP1</label>
																	<input class="custom-otp-options js-webform-input-mask form-text" autocomplete="off" data-inputmask-mask="9 = numeric" type="text" id="edit-otp1-items-0-item-" name="otp1[items][0][_item_]" value="" size="60" maxlength="1" />
																</div>
															</td>
														</tr>
														<tr class="even">
															<td>
																<div class="js-form-item form-item js-form-type-textfield form-type-textfield js-form-item-otp1-items-1--item- form-item-otp1-items-1--item- form-no-label">
																	<label for="edit-otp1-items-1-item-" class="visually-hidden">OTP1</label>
																	<input class="custom-otp-options js-webform-input-mask form-text" autocomplete="off" data-inputmask-mask="9 = numeric" type="text" id="edit-otp1-items-1-item-" name="otp1[items][1][_item_]" value="" size="60" maxlength="1" />
																</div>
															</td>
														</tr>
														<tr class="odd">
															<td>
																<div class="js-form-item form-item js-form-type-textfield form-type-textfield js-form-item-otp1-items-2--item- form-item-otp1-items-2--item- form-no-label">
																	<label for="edit-otp1-items-2-item-" class="visually-hidden">OTP1</label>
																	<input class="custom-otp-options js-webform-input-mask form-text" autocomplete="off" data-inputmask-mask="9 = numeric" type="text" id="edit-otp1-items-2-item-" name="otp1[items][2][_item_]" value="" size="60" maxlength="1" />
																</div>
															</td>
														</tr>
														<tr class="even">
															<td>
																<div class="js-form-item form-item js-form-type-textfield form-type-textfield js-form-item-otp1-items-3--item- form-item-otp1-items-3--item- form-no-label">
																	<label for="edit-otp1-items-3-item-" class="visually-hidden">OTP1</label>
																	<input class="custom-otp-options js-webform-input-mask form-text" autocomplete="off" data-inputmask-mask="9 = numeric" type="text" id="edit-otp1-items-3-item-" name="otp1[items][3][_item_]" value="" size="60" maxlength="1" />
																</div>
															</td>
														</tr>
														<tr class="odd">
															<td>
																<div class="js-form-item form-item js-form-type-textfield form-type-textfield js-form-item-otp1-items-4--item- form-item-otp1-items-4--item- form-no-label">
																	<label for="edit-otp1-items-4-item-" class="visually-hidden">OTP1</label>
																	<input class="custom-otp-options js-webform-input-mask form-text" autocomplete="off" data-inputmask-mask="9 = numeric" type="text" id="edit-otp1-items-4-item-" name="otp1[items][4][_item_]" value="" size="60" maxlength="1" />
																</div>
															</td>
														</tr>
														<tr class="even">
															<td>
																<div class="js-form-item form-item js-form-type-textfield form-type-textfield js-form-item-otp1-items-5--item- form-item-otp1-items-5--item- form-no-label">
																	<label for="edit-otp1-items-5-item-" class="visually-hidden">OTP1</label>
																	<input class="custom-otp-options js-webform-input-mask form-text" autocomplete="off" data-inputmask-mask="9 = numeric" type="text" id="edit-otp1-items-5-item-" name="otp1[items][5][_item_]" value="" size="60" maxlength="1" />
																</div>
															</td>
														</tr>
													</tbody>
												</table>
											</div>
											<div class="description">
												<div id="edit-otp1--description" class="webform-element-description">
													<div class="resend-otp1">
														<a class="use-ajax" href="/shcresend-otp/" id="resend-otp">Resend OTP</a>:
														<div id="timer">39</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="form-actions webform-actions js-form-wrapper form-wrapper" id="edit-actions">
									<input formnovalidate="formnovalidate" class="webform-button--previous change-mobile-no-home button js-form-submit form-submit" type="submit" id="edit-actions-wizard-prev" name="op" value="Change Phone Number" />
									<input class="webform-button--submit submit-button-home button button--primary js-form-submit form-submit" type="submit" id="edit-actions-submit" name="op" value="Submit" />
								</div>
								<input autocomplete="off" type="hidden" name="form_build_id" value="form-MDZgM_VhmIy-x1TLWAJoY9rTHpsFaDC1yeDpN4LuwNI" />
								<input type="hidden" name="form_id" value="webform_submission_schedule_a_home_collection_add_form" />
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-12 col-sm-12" >
				<div class="flexslider23" id="hero-slider44" data-aos="fade-left" data-aos-duration="1000">
					<div class="region region-home-slider">
						<div class="views-element-container block block-views block-views-blockslider-block-1" id="block-views-block-slider-block-1">
							<div>
								<div class="view view-slider view-id-slider view-display-id-block_1 js-view-dom-id-e70376fdcf1722c7c8809861a200b8d3cdaf394b5883672947651d2e3a302c5d">
									<div class="view-content">
										<div>
											<div id="homeflexslider" class="flexslider optionset-default">
												<ul class="slides">
													<li>
														<div class="views-field views-field-field-image">
															<div class="field-content">
																<img src="/assets/images/PL_Diwali%20package_800%20w%20x%20593%20h.jpg" width="800" height="593" alt="" loading="lazy" typeof="foaf:Image" />
															</div>
														</div>
														<div class="flex-caption">
															<p></p>
															<p></p>
															<p></p>
															<a href="https://bit.ly/3Sg7CwE" title="see-details" target="_blank">See Details</a>
														</div>
													</li>
													<li>
														<div class="views-field views-field-field-image">
															<div class="field-content">
																<img src="/assets/images/Web-image-4.jpg" width="800" height="593" alt="rt pcr test for covid 19" loading="lazy" typeof="foaf:Image" />
															</div>
														</div>
														<div class="flex-caption">
															<h3>COVID-19 RT PCR Test</h3>
															<p>The Gold Standard test for detecting Coronavirus</p>
															<a href="/know-about-covid-19/" title="see-details" target="_blank">See Details</a>
														</div>
													</li>
													<li>
														<div class="views-field views-field-field-image">
															<div class="field-content">
																<img src="/assets/images/Web-image-2.jpg" width="800" height="593" alt="blood test at home near me" loading="lazy" typeof="foaf:Image" />
															</div>
														</div>
														<div class="flex-caption">
															<h3>Worried about going out for a blood test?<br />Relax, we will come to you.</h3>
															<p>Book sample collection at the comfort of your home</p>
															<a href="/book-test/" title="see-details" target="_blank">See Details</a>
														</div>
													</li>
													<li>
														<div class="views-field views-field-field-image">
															<div class="field-content">
																<img src="/assets/images/Web-images-1.jpg" width="800" height="593" alt="Recovery status of covid 19" loading="lazy" typeof="foaf:Image" />
															</div>
														</div>
														<div class="flex-caption"><h3>Have you recovered completely from<br />COVID-19?</h3>
															<p>Know your recovery status with our COVID Recovery Panels</p>
															<a href="/book-test/" title="see-details" target="_blank">See Details</a>
														</div>
													</li>
													<li>
														<div class="views-field views-field-field-image">
															<div class="field-content">
																<img src="/assets/images/Web-image-3_0.jpg" width="800" height="593" alt="Health checkup packages" loading="lazy" typeof="foaf:Image" />
															</div>
														</div>
														<div class="flex-caption">
															<h3>Choose from a range of comprehensive<br />full body health check-up packages.</h3>
															<p>for you and your family</p>
															<a href="/book-test?sort_by=2" title="see-details" target="_blank">See Details</a>
														</div>
													</li>
													<li>
														<div class="views-field views-field-field-image">
															<div class="field-content">
																<img src="/assets/images/Web-image-5.jpg" width="800" height="593" alt="Covid 19 antibody test" loading="lazy" typeof="foaf:Image" />
															</div>
														</div>
														<div class="flex-caption">
															<h3>COVID-19 Antibody Test</h3>
															<p>Know your Antibody levels and the effectiveness of COVID vaccine</p>
															<a href="/book-test/" title="see-details" target="_blank">See Details</a>
														</div>
													</li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- hero section end -->

templates/homepage/home.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{{ form.media }}
{{ aforms.media }}
{{ bforms.media }}
{% endblock %}

{% block extra_style %}
{% endblock %}

{% block content %}

{% include "homepage/hero.html" %}

{% include "homepage/health_packages.html" %}

{% include "homepage/tests_section.html" %}

{% endblock %}


{% block extra_jscript %}
{% endblock %}

templates/homepage/home_schedule.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extra_style %}
<link href="{% static 'css/based.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}

<!-- main header section end -->
<section class="sec1">
	<div class="container">
		<div class="row">
			<div class="breadcam-bg breadcam">
				<div class="container common-container four_content ">
					<div class="region region-highlighted">
						<div class="hidden"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% include "core/hero_schedule.html" %}

{% include "core/health_packages.html" %}

{% include "core/tests_section.html" %}

{% endblock %}


<script src="{% static 'js/modernizr.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/modernizr-additional-tests.js' %}" type="text/javascript"></script>

{% block extra_jscript %}
{% endblock %}

templates/homepage/tests_section.html
<!-- tests section start -->
<section class="home_section section_pb">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-lg-6">
				<h2 class="home_title">Test by Body Parts</h2>
				<div class="body_part">
					<a href="#" class="part_list">
						<img src="assets/images/icons/heart.png" alt="">
						<p>Heart</p>
					</a>
					<a href="#" class="part_list">
						<img src="assets/images/icons/liver.png" alt="">
						<p>Liver</p>
					</a>

					<a href="#" class="part_list">
						<img src="assets/images/icons/kidney.png" alt="">
						<p>Kidney</p>
					</a><a href="#" class="part_list">
						<img src="assets/images/icons/bone.png" alt="">
						<p>Bone</p>
					</a>
					<a href="#" class="part_list">
						<img src="assets/images/icons/thyroid.png" alt="">
						<p>Thyroid</p>
					</a>
				</div>
				<h2 class="home_title mt-4">Test by Condition</h2>
				<div class="body_part">
					<a href="#" class="part_list">
						<img src="assets/images/icons/diabetes.png" alt="">
						<p>Diabetes</p>
					</a>

					<a href="#" class="part_list">
						<img src="assets/images/icons/kidney.png" alt="">
						<p>Kidney</p>
					</a>
					<a href="#" class="part_list">
						<img src="assets/images/icons/thyroid.png" alt="">
						<p>Thyroid</p>
					</a>
				</div>
			</div>
			<div class="col-md-12 col-lg-6">
				<h2 class="home_title mobile_margin2">Most Popular Tests</h2>

				{% for item in products %}
				<div class="pop_tests">
					<img src="/assets/images/scope.png" alt="">
					<div class="flex-fill">
						<p class="m-0">
							<a class="product_detail" href="{{ item.get_absolute_url }}" title="{{ item.title }}">{{ item.title }}</a>
						</p>
					</div>
					<a href="{% url 'shop:add_to_cart' item.pk %}" class="buy_now_list">Buy Now</a>
				</div>
				{% endfor %}

			</div>
		</div>
	</div>
</section>
<!-- tests section end -->