order/urls.py
from django.urls import path, re_path

from .views import *

app_name='order'

urlpatterns = [
    path('', checkout, name='checkout'),
    path('callback/', callback, name='callback'),
    # path('paymenthandler/', paymenthandler, name='paymenthandler'),
]

shop/urls.py
from django.urls import path, re_path

from .views import *

app_name='shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('add-to-cart/<pk>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove_from_cart'),
	path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce_quantity_item'),
    # path("callback/", callback, name="callback"),
    # path('order-summary/', order_summary, name='order_summary'),
    # path('order/', order, name='order'),
    # path('payment/<payment_option>/', payment, name='payment'),
    # path('paymenthandler/', paymenthandler, name='paymenthandler'),
    # path('', FacetedSearchView.as_view(), name='haystack_search'),
    # path('find/', FacetedSearchView.as_view(), name='haystack_search'),
    # path('product/(?P<slug>[\w-]+)/$', ProductView.as_view(), name='product'),
    # path('search/autocomplete/$', autocomplete),
]

shrinivasdiagnostics/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

from shop.views import *
from order.views import *
from accounts.views import *

from djoser import views as djoser_views
# from rest_framework_jwt import views as jwt_views

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('admin/', include('massadmin.urls')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('accounts.urls')),

    path('book-test/', include('shop.urls')),
    path('package-description/<pk>/', product_detail, name='product_detail'),
    path('shopping-cart/', shopping_cart, name='shopping_cart'),
    # path('order/', order, name='order'),
    path('checkout/', include('order.urls')),
    path('checkout/', include('address.urls')),
    # path("callback/", callback, name="callback"),
	# path('payment/', paymenthandler, name='paymenthandler'),
    # path("payment/", order_payment, name="order_payment"),
    path('my-orders/', my_orders, name='my_orders'),

    path('search/', include('haystack.urls')),
    path('book-test/autocomplete/', productlist_search, name='productlist_search'),
    # path('search/autocomplete/', productlist_search(view_class=SearchView, template='index.html', form_class=ProductSearchForm), name='haystack_search'),

    path('api/', include('djoser.urls')),
    path('api/', include('djoser.urls.jwt')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/forms.py
from django import forms

from .models import *
from accounts.models import *
from address.models import *

from haystack.forms import FacetedSearchForm, SearchForm
from haystack.inputs import Exact

from crispy_forms.bootstrap import *
from crispy_forms.helper import *
from crispy_forms.layout import *

# from easy_select2 import *

PRODUCT_QUANTITY_CHOICES=[(i,str(i)) for i in range(1,21)]

PAYMENT = (
	('S', 'Stripe'),
	('P', 'PayPal')
)

class CartAddProductForm(forms.Form):
	quantity=forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
	update=forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)


class CheckoutForm(forms.Form):
	street_address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '1234 Main St'}))
	apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apartment or suite'}))
	# country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={'class': 'custom-select d-block w-100'}))
	zip = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	same_billing_address = forms.BooleanField(required=False)
	save_info = forms.BooleanField(required=False)
	payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT)


class ProductFindForm(forms.ModelForm):
	# Meta = select2_modelform_meta(Product)

	class Meta:
		model = Product
		# fields = ('title')
		fields = '__all__'
		widgets = {
			# "title": MarketWidget,
			# "title": apply_select2(forms.Select),
		}

	# title = forms.ModelChoiceField(required=True, label="", queryset=Product.objects.all().order_by('available'), widget=Select2(attrs={'class': "test_search_input_field search__test_package box"}))
	# longitude = forms.ModelChoiceField(label=u"City", queryset=City.objects.all(), widget=ModelSelect2Widget(model=City, search_fields=['longitude__icontains'], dependent_fields={'city': 'city'}, max_results=500,))
	# aspect = forms.MultipleChoiceField(required=False, label="Aspect: ", widget=forms.CheckboxSelectMultiple(attrs={'class': "form-control"}), choices=ASPECT_GEOMETRY_CHOICES)

	# def __init__(self, *args, **kwargs):
	# 	super().__init__(*args, **kwargs)
	# 	self.helper = FormHelper()
	# 	self.helper.layout = Layout(Div(InlineRadios('')),)


class ProductSearchForm(SearchForm):
	title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '1234 Main St'}))

	def search(self):
		# First, store the SearchQuerySet received from other processing.
		sqs = super().search()

		if not self.is_valid():
			return self.no_query_found()

		if self.cleaned_data['title']:
			# sqs = sqs.filter(available=True)
			sqs = sqs.filter(available=self.cleaned_data['title'])

		return sqs

class FacetedProductSearchForm(FacetedSearchForm):

	def __init__(self, *args, **kwargs):
		data = dict(kwargs.get("data", []))
		self.title = data.get('title', [])
		super(FacetedProductSearchForm, self).__init__(*args, **kwargs)

	def search(self):
		sqs = super(FacetedProductSearchForm, self).search()

		if self.title:
			query = None
			for title in self.title:
				if query:
					query += u' OR '
				else:
					query = u''
				query += u'"%s"' % sqs.query.clean(title)
			sqs = sqs.narrow(u'title_exact:%s' % query)
		return sqs

shop/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, TemplateView, View

from .models import *
from .forms import *

from accounts.models import *
from accounts.forms import *

from order.models import *

from rest_framework.decorators import api_view, renderer_classes
from rest_framework.response import Response

from haystack.generic_views import FacetedSearchView as BaseFacetedSearchView, SearchView
from haystack.query import SearchQuerySet
from email_split import email_split

# import json
import simplejson as json
import uuid
import shortuuid


def productlist_search(request):
	sqs = None

	if request.method == "GET":
		if "q" in request.GET:
			query = str(request.GET.get("q"))
			search_models = []
			search_models = [Product]
			sqs = SearchQuerySet().all().filter(q=query).models(*search_models)
			# sqs = SearchQuerySet().autocomplete(title_auto=query).models(*search_models)
			# suggestions = [result.title for result in sqs]
			# suggestions = [{'text':result.title, 'url':generate_url(result), }
			# 	for result in sqs
			# ]

			# the_data = json.dumps(
			# {
			# 	'sqs': suggestions,
				# 'query': query
				# 'sqs': sqs
			# })

			context = {
				'sqs': sqs,
			}

			# return JsonResponse({'sqs': suggestions})
	return render(request, "shop/product_list.html", context)
	# return HttpResponse(the_data, content_type='application/json')
	# return HttpResponse(the_data, mimetype='application/json')
	# return JsonResponse(the_data, safe=False)
	# return JsonResponse({'sqs': suggestions})

# @api_view(['POST'])
# def productlist_search(request):
# 	name = request.data['name']
# 	customer = SearchQuerySet().models(Customer).autocomplete(first_name__startswith=name)

# 	searched_data = []
# 	for i in customer:
# 		all_results = {"first_name": i.first_name, "last_name": i.last_name, "balance": i.balance, "status": i.customer_status,}
# 		searched_data.append(all_results)

# 	return Response(searched_data)


def product_list(request, category_slug=None):
	page_title = _('Book Blood Test Online in India with Ease with Shrinivas Diagnostics Labs')
	category = None
	categories = Category.objects.all()
	object_list = Product.objects.filter(available=True)
	user_id = request.user.is_authenticated
	user_order = Order.objects.filter(user=user_id, item_order=False).count()

	is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		object_list = object_list.filter(category=category)

	if request.method == "GET":
	# if request.method == "GET" and is_ajax:
		form = ProductFindForm()

		if form.is_valid():
			# save_geoastro.natalstock_pluto = get_geo_pluto(get_tz)
			# save_geoastro.save()

			messages.warning(request, "Sukses")
			# return redirect('core:homepage')
			return render(request, 'shop/product_list.html', context)
		else:
			messages.warning(request, form.errors)


	context = {
		'page_title': page_title,
		'category': category,
		'categories': categories,
		'object_list': object_list,
		'user_order': user_order,
		'form': form,
		# 'sqs': sqs,
	}

	return render(request, 'shop/product_list.html', context)


@login_required()
def product_detail(request, pk):
	product = get_object_or_404(Product, id=pk, available=True)
	page_title = product
	user_id = Profile.objects.get(email=request.user)
	user_order = Order.objects.filter(user=user_id, item_order=False).count()
	cart_product_form=CartAddProductForm()

	context = {
		'page_title': page_title,
		'product': product,
		'cart_product_form': cart_product_form,
		'user_order': user_order,
	}

	return render(request, 'shop/product_detail.html', context)


@login_required()
def shopping_cart(request):
	page_title = _('Cart | ShrinivasDiagnostic')
	user_id = Profile.objects.get(email=request.user)
	user_order = Order.objects.filter(user=user_id, item_order=False).count()
	total_price = request.GET.get('total_price')

	try:
		cart_order = Checkout.objects.get(user=request.user, ordered=False)
		# product = Product.objects.get(user=request.user, order=False)
		products = Product.objects.filter(available=True)
		product = products.count()
		# get_total_item_price = products.price

		if user_order == 0:
			display_result = True
		else:
			display_result = False

		context = {
			'cart_order': cart_order,
			'products': products,
			'user_order': user_order,
			'page_title': page_title,
			'display_result': display_result,
		}
		return render(request, 'shop/shopping_cart.html', context)
	except ObjectDoesNotExist:
		messages.error(request, "You do not have an order")
		return redirect("shop:product_list")


@login_required()
def add_to_cart(request, pk):
	item = get_object_or_404(Product, pk=pk)
	order_item, created = Order.objects.get_or_create(product=item, user=request.user, item_order=False)
	order_qs = Checkout.objects.filter(user=request.user, ordered=False)
	user_id = Profile.objects.get(email=request.user)
	email = user_id.email

	if order_qs.exists():
		order = order_qs[0]

		if order.items.filter(product__pk=item.pk).exists():
			order_item.quantity += 1
			order_item.save()
			messages.info(request, "Added quantity Item")
			return redirect("shopping_cart")
		else:
			order.items.add(order_item)
			messages.info(request, "Item \""+order_item.product.title+"\" added to your cart")
			return redirect("shopping_cart")
	else:
		checkout_date = timezone.now()
		unique_id = uuid.uuid4()
		unique_id = str(unique_id)
		email = email_split(email)
		# unique_id = email.local + "-" + unique_id
		unique_id = shortuuid.ShortUUID(alphabet="abcdefg1234").random(length=22)
		# print(email.domain)
		# print(email.local)
		order = Checkout.objects.create(user=request.user, payment_type=unique_id, checkout_date=checkout_date)
		order.items.add(order_item)
		messages.info(request, "Item \""+order_item.product.title+"\" added to your cart")
		return redirect("shopping_cart")


def remove_from_cart(request, pk):
	item = get_object_or_404(Product, pk=pk)
	order_qs = Checkout.objects.filter(user=request.user, ordered=False)

	if order_qs.exists():
		order = order_qs[0]
		if order.items.filter(product__pk=item.pk).exists():
			order_item = Order.objects.filter(product=item, user=request.user, item_order=False)[0]
			order_item.delete()
			messages.info(request, "Item \""+order_item.product.title+"\" remove from your cart")
			return redirect("shopping_cart")
		else:
			messages.info(request, "This Item not in your cart")
			return redirect("shopping_cart")
	else:
		messages.info(request, "You do not have an Order")
		return redirect("shopping_cart")


def reduce_quantity_item(request, pk):
	item = get_object_or_404(Product, pk=pk)
	order_qs = Checkout.objects.filter(user=request.user, ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		if order.items.filter(product__pk=item.pk).exists():
			order_item = Order.objects.filter(product=item, user=request.user, item_order=False)[0]
			if order_item.quantity > 1:
				order_item.quantity -= 1
				order_item.save()
			else:
				order_item.delete()
				messages.info(request, "Item quantity was updated")
			return redirect("shopping_cart")
		else:
			messages.info(request, "This Item not in your cart")
			return redirect("shopping_cart")
	else:
		messages.info(request, "You do not have an Order")
		return redirect("shopping_cart")

def get_add_to_cart_url(request, pk):
	return reverse("shop:add_to_cart", pk=pk)


def autocomplete(request):
	sqs = SearchQuerySet().autocomplete(title_auto=request.GET.get('q', ''))[:5]
	# sqs = SearchQuerySet().autocomplete(title_auto='q')
	# sqs = SearchQuerySet().filter(title_auto=request.GET.get('q', ''))
	# sqs = SearchQuerySet().autocomplete(title_auto=request.POST.get('q', ''))
	# sqs = SearchQuerySet().filter(title_auto=request.GET.get('q', ''))
	# sqs = SearchQuerySet().models(Product).autocomplete(title_auto=request.GET.get('q', ''))
	# sqs = SearchQuerySet().filter(title_auto=request.GET.get('q', ''))
	# sqs = SearchQuerySet().autocomplete(title_auto=request.GET.get('q', ''))

	# s = []
	# for result in sqs:
	# 	d = {"value": result.title, "data": result.object.slug}
	# 	s.append(d)
	# output = {'suggestions': s}

	suggestions = [result.title for result in sqs]
	# Make sure you return a JSON object, not a bare list.
	# Otherwise, you could be vulnerable to an XSS attack.
	the_data = json.dumps(
	{
		'results': suggestions
	})
	# return JsonResponse(output)
	return HttpResponse(the_data, content_type='application/json')


class FacetedSearchView(BaseFacetedSearchView):

	form_class = ProductSearchForm
	facet_fields = ['title']
	template_name = 'shop/product_list.html'
	paginate_by = 3
	context_object_name = 'object_list'



templates/shop/product_detail.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block extra_style %}
{% endblock %}



{% block content %}

<section class="test-detail-inner">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<div class="breadcrumb-inner">
					<ul>
						<a href="/">
							<li>Home</li>
						</a>
						<a href="/book-test/">
							<li>Test & Packages</li>
						</a>
						<li class="current">Test Details</li>
					</ul>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-5 col-sm-12">
				<div class="download-report">
					<div class="flex-inline head">
						<h6>Sample Report</h6>
					</div>
					<div class="report-data">
						<img src="/assets/images/pdf-img.png" class="img-fluid">
					</div>
					<!-- <a href="javascript:void(0)" id="share_report" class="action">Send report to email</a> -->
				</div>
			</div>
			<div class="col-md-7 col-sm-12">
				<div class="inner-test-details">
					<div class="flex-inline head">
						<div class="name">
							<div class="img">
								<img src="/assets/images/scope-bg.svg" class="img-fluid">
							</div>
							<h4>{{ product.title }}</h4>
						</div>
						<p class="price">&#8377; {{ product.price }}/-</p>
					</div>
					<p class="tags">TAT</p>
					<div class="inner-tabs">
						<div class="flex-inline">
							<ul class="nav nav-tabs" id="myTab" role="tablist">
								<li class="nav-item">
									<a class="nav-link " id="doctor-tab" data-toggle="tab" href="#doctor" role="tab" aria-controls="home" aria-selected="true">Doctors</a>
								</li>
								<li class="nav-item">
									<a class="nav-link active" id="patient-tab" data-toggle="tab" href="#patient" role="tab" aria-controls="profile" aria-selected="false">Patients</a>
								</li>
							</ul>
							<a href="#" class="share-test-details dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <img src="/assets/images/upload.svg"> Share Test Details</a>
							<div class="dropdown-menu share-details" aria-labelledby="dropdownMenuButton">
								<a class="dropdown-item share-email" href="javascript:void(0)"> <img src="/assets/images/email.png"> Email</a>
								<a class="dropdown-item share-sms" href="javascript:void(0)"> <img src="/assets/images/sms.png"> SMS </a>
							</div>
						</div>

						<!-- share report sidebar -->
						<div class="sidebar-share-details">
							<a href="#" class="close-sidebar" id="description-close"><img src="/assets/images/close.png" class="img-fluid"></a>
							<div class="sidebar-inner">
								<div class="header">
									<img src="/assets/images/white-logo.png">
								</div>
								<div class="sidebar">
									<h3 class="heading-small-v-2">Share Details</h3>
									<form action="/tests/test_public/send_sample_report" class="schedule-home-form" method="post">
										<input type="hidden" name="csrf_test_name" value="b21ee350821c7411f99faabeecd9c93d" />
										<input type="hidden" id="email_type" name="email_type" value="" />
										<input type="hidden" id="report_link" name="report_link" value="" />
										<input type="hidden" id="test_id" name="test_id" value="10056" />
										<input type="hidden" id="item_type" name="item_type" value="2" />
										<small>Your Email address</small>
										<input class="m-b-20 custom-form-control" required name="email" type="email" placeholder="Email">
										<button type="submit" class="btn-2">Send</button>
									</form>
								</div>
							</div>
						</div>

						<!-- share sms sidebar -->
						<div class="sidebar-sharesms-details">
							<a href="#" class="close-sidebar" id="sms-close"><img src="/assets/images/close.png" class="img-fluid"></a>
							<div class="sidebar-inner">
								<div class="header">
									<img src="/assets/images/white-logo.png">
								</div>
								<div class="sidebar">
									<h3 class="heading-small-v-2">Share Details</h3>
									<form action="/tests/test_public/send_sms" class="schedule-home-form" method="post">
										<input type="hidden" name="csrf_test_name" value="b21ee350821c7411f99faabeecd9c93d" />
										<input type="hidden" id="test_id" name="test_id" value="10056" />
										<input type="hidden" id="item_type" name="item_type" value="2" />
										<small>Your Mobile Number</small>
										<input class="m-b-20 custom-form-control" required name="mobile" type="number" maxlength="10" minlength="10" placeholder="Mobile No">
										<button type="submit" class="btn-2">Send</button>
									</form>
								</div>
							</div>
						</div>

						<div class="tab-content" id="doctor-patient-info">
							<div class="tab-pane fade " id="doctor" role="tabpanel" aria-labelledby="doctor-tab">
								<div class="flex-inline m-b-15 align-top">
									<div class="info">
										<p><strong>Component</strong></p>
										<p>{{ product.component }}</p>
									</div>

									<div class="info">
										<p><strong>Specimen</strong></p>
										<p>{{ product.speciment }}</p>
									</div>
								</div>
								<div class="flex-inline m-b-15 align-top">
									<div class="info">
										<p><strong>Method</strong></p>
										<p>{{ product.method }}</p>
									</div>
									<div class="info">
										<p><strong>Cut Off Time</strong></p>
										<p>{{ product.cutofftime }}</p>
									</div>
								</div>
								<div class="flex-inline m-b-15 align-top">
									<div class="info">
										<p><strong>Quantity and Temperature</strong></p>
										<p>{{ product.quantitytemperature }}</p>
									</div>
								</div>

								<div class="devider"></div>
								<div class="flex-inline action">
									<form action="{% url 'shop:add_to_cart' product.pk %}" class="form-inline add-to-cart-form" method="post">
										{% csrf_token %}
										<button type="submit" class="button_add_to_cart ">Buy Now</button>
									</form>
									<form action="{% url 'shop:add_to_cart' product.pk %}" class="form-inline add-to-cart-form" method="post">
										{% csrf_token %}
										<button type="submit" class="button_add_to_cart add-to-cart-btn">Add to Cart</button>
									</form>
								</div>
							</div>

							<div class="tab-pane fade show active" id="patient" role="tabpanel" aria-labelledby="patient-tab">
								<div class="flex-inline m-b-15 align-top">
									<div class="info">
										<p><strong>Pre-Requisites</strong></p>
										<p>{{ product.prerequisites }}</p>
									</div>
									<div class="info" style="margin-left:4px">
										<p><strong>TAT</strong></p>
										<p>Sample Cut off : {{ product.samplecutoff }}, <br>Report : {{ product.report }}<br>(NOTE:{{ product.note }})</p>
										<!--TAT will start after sample reaches the lab-->
									</div>
								</div>
								<div class="devider"></div>
								<div class="flex-inline action">
									<form action="{% url 'shop:add_to_cart' product.pk %}" class="form-inline add-to-cart-form" method="post">
										{% csrf_token %}
										<button type="submit" class="button_add_to_cart ">Buy Now</button>
									</form>
									<form action="{% url 'shop:add_to_cart' product.pk %}" class="form-inline add-to-cart-form" method="post">
										{% csrf_token %}
										<button type="submit" class="button_add_to_cart add-to-cart-btn">Add to Cart</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

<script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/select2.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/site.js' %}" type="text/javascript"></script>
<script src="{% static 'js/toastr.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.flexslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.easy-autocomplete.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/sweetalert2.min.js' %}" type="text/javascript"></script>

{% block extra_jscript %}
{% endblock %}

templates/shop/shopping_cart.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block extra_style %}
{% endblock %}


{% block content %}
<!-- Inner checkout items start -->
	<section class="search_section">
		<div class="container">
			<div class="row">

				<div class="col-md-8">

					<div class="flex_and_justify">
						<div>
							<h2 class="home_title">Order Overview</h2>
						</div>
						<div>
							<a href="/book-test/" class="btn_cart"><i class="fa-solid fa-plus"></i> Add Tests</a>
						</div>
					</div>

					{% for item in cart_order.items.all %}
					<div class="cart_box">
						<div class="cart_left">
							<h4>{{ item.product.title }}</h4>
							<a href="{% url 'shop:remove_from_cart' item.product.pk %}">Remove</a>
						</div>
						<div class="cart_right">
							<h4>₹ {{ item.product.price }}</h4>
							<div class="input-group number-spinner">
								<div class="input-group-prepend">
									<button class="bbtn bl" data-dir="dwn" type="button">
										<a href="{% url 'shop:remove_from_cart' item.product.pk %}"><i class="fas fa-minus"></i></a>
									</button>
								</div>
								<input type="text" class=" text-center" value="{{ item.quantity }}">
								<div class="input-group-append">
									<button class="bbtn br" data-dir="up" type="button">
										<a href="{% url 'shop:add_to_cart' item.product.pk %}"><i class="fas fa-plus"></i></a>
									</button>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}

				</div>

				<div class="col-md-4">
					<h2 class="home_title">Summary</h2>
					{% if cart_order.get_total_price %}
					<div class="sub_total_box">
						<div class="total_box">
							<p>Subtotal</p>
							<p>₹ {{ cart_order.get_total_price }}</p>
						</div>
						<div class="total_box">
							<p><b>Total</b></p>
							<p><b>₹ {{ cart_order.get_total_price }}</b></p>
						</div>
						<a href="{% url 'order:checkout' %}"><button class="btn_submit mt-4">Proceed to Checkout</button></a>
					</div>
					{% endif %}
				</div>

			</div>
		</div>
	</section>

	<section class="cart_section2">
		<div class="container">
			<h2 class="home_title">People also booked these tests</h2>
			<div id="list-slider" class="owl-carousel owl-theme list_slider">

				{% for item in products %}
				<div class="item">
					<div class="listing_box">
						<div class="listing_header">
							<div class="best_seller">Best Seller</div>
							<h3><a class="product_detail" href="{{ item.get_absolute_url }}" title="{{ item.title }}">{{ item.title }}</a></h3>
							<p>₹{{ item.discount_price }} <span>₹{{ item.price }}</span></p>

							<div class="testes_tag">Tests</div>
							<form action="{% url 'order:checkout' %}" method="POST">
							{% csrf_token %}
								<a href="{% url 'shop:add_to_cart' item.pk %}" class="add_cart">Add to Cart</a>
							</form>
						</div>
						<div class="listing_body custom_scroll">
							<p class="l_title">{{ item.category }}</p>
							<p class="l_text">{{ item.prerequisites }}</p>
							<p class="l_text">{{ item.samplecutoff }}</p>
							<p class="l_text">{{ item.report }}</p>
							<p class="l_title">{{ item.category }}</p>
							<p class="l_text">{{ item.speciment }}</p>
							<p class="l_text">{{ item.method }}</p>
							<p class="l_title">{{ item.category }}</p>
							<p class="l_text">{{ item.quantitytemperature }}</p>
							<p class="l_text">{{ item.quantitytemperature }}</p>
						</div>
					</div>
				</div>
				{% endfor %}

			</div>
		</div>
	</section>

{% endblock %}

{% block extra_jscript %}
<script type='text/javascript'>
$(document).ready(function()
{
	$(document).on('click', '.number-spinner button', function()
	{
		var btn = $(this),
		oldValue = btn.closest('.number-spinner').find('input').val().trim(),
		newVal = 0;

		if (btn.attr('data-dir') == 'up')
		{
			newVal = parseInt(oldValue) + 1;
		}
		else
		{
			if (oldValue > 1)
			{
				newVal = parseInt(oldValue) - 1;
			}
			else
			{
				newVal = 1;
			}
		}
		btn.closest('.number-spinner').find('input').val(newVal);
	});

	var total_price = "{{ cart_order.get_total_price }}";
	// var total_price = document.querySelector('.total-charges').innerHTML;
	// var total_price = parseFloat(total_price.replace(/₹/g, ""));
	total_price = Number(total_price.replace(/[^0-9\.-]+/g,""));
	console.log("total_price", total_price);

	$.ajax(
	{
		url:'{% url "shopping_cart" %}',
		data:
		{
			'total_price': total_price,
		},

		success: function(data)
		{
			// console.log("total_price: ", total_price);
			// console.log("total_price: ", total_price);
		},
	});

});
</script>
{% endblock %}