address/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView, LoginView
from django.urls import path, re_path, include
from django.views.generic import RedirectView

from .views import *
from . import views

app_name = 'address'

urlpatterns = [
    path('add/', create_billingaddress, name='create_billingaddress'),
    path('change-address/<id>/', update_billingaddress, name='update_billingaddress'),
]

order/urls.py
from django.urls import path, re_path

from .views import *

app_name='order'

urlpatterns = [
    path('', checkout, name='checkout'),
    path('callback/', callback, name='callback'),
    # path('paymenthandler/', paymenthandler, name='paymenthandler'),
]

shop/urls.py
from django.urls import path, re_path

from .views import *

app_name='shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('add-to-cart/<pk>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<pk>/', remove_from_cart, name='remove_from_cart'),
	path('reduce-quantity-item/<pk>/', reduce_quantity_item, name='reduce_quantity_item'),
    # path("callback/", callback, name="callback"),
    # path('order-summary/', order_summary, name='order_summary'),
    # path('order/', order, name='order'),
    # path('payment/<payment_option>/', payment, name='payment'),
    # path('paymenthandler/', paymenthandler, name='paymenthandler'),
    # path('', FacetedSearchView.as_view(), name='haystack_search'),
    # path('find/', FacetedSearchView.as_view(), name='haystack_search'),
    # path('product/(?P<slug>[\w-]+)/$', ProductView.as_view(), name='product'),
    # path('search/autocomplete/$', autocomplete),
]

shrinivasdiagnostics/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

from shop.views import *
from order.views import *
from accounts.views import *

from djoser import views as djoser_views
# from rest_framework_jwt import views as jwt_views

urlpatterns = [
    path('', include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('admin/', include('massadmin.urls')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('accounts.urls')),

    path('book-test/', include('shop.urls')),
    path('package-description/<pk>/', product_detail, name='product_detail'),
    path('shopping-cart/', shopping_cart, name='shopping_cart'),
    # path('order/', order, name='order'),
    path('checkout/', include('order.urls')),
    path('checkout/', include('address.urls')),
    # path("callback/", callback, name="callback"),
	# path('payment/', paymenthandler, name='paymenthandler'),
    # path("payment/", order_payment, name="order_payment"),
    path('my-orders/', my_orders, name='my_orders'),

    path('search/', include('haystack.urls')),
    path('book-test/autocomplete/', productlist_search, name='productlist_search'),
    # path('search/autocomplete/', productlist_search(view_class=SearchView, template='index.html', form_class=ProductSearchForm), name='haystack_search'),

    path('api/', include('djoser.urls')),
    path('api/', include('djoser.urls.jwt')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/checkout/add_address.html
{% extends 'base_shop.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block extra_style %}
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/style_shopdetail.css' %}" rel="stylesheet" type="text/css">
{% endblock %}


{% block content %}

<!-- Inner checkout items start -->
<div class="inner-checkout">
	<div class="container">

		<div class="row">

			<div class="col-lg-8 col-md-8 col-sm-12">
				<div class="flex-inline">
					<div class="heading-small-v-2">Add Billing Address{{ total_payment.get_final_price }}</div>
					<a href="/book-test/" class="btn-1 btn">+ Add Tests</a>
				</div>

				<div class="accordian checkout-collapse">

					<!-- Sidebar patient add -->
					<!-- item-2 -->
					<div id="checkout-collapse-item-2">
						<div class="card">
							<div class="card-header" id="headingTwo">
								<h2 class="mb-0">
									<button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapse-item-2" id="billing_address" aria-expanded="false" aria-controls="collapse-item-2">1. Billing Address</button>
								</h2>
							</div>

							<style>
							.form-group .easy-autocomplete
							{
								width: 100%!important;
							}
							</style>

							<div id="collapse-item-2" class="collapse checkout-collapse-body" aria-labelledby="headingTwo" data-parent="#checkout-collapse-item-2">
								<div class="card-body">
									<div class="row billing-address">
										<div class="col-md-6">
											<div class="box">
												{% for item in user_address %}
												<input type="radio" name="default_address" data-address-id="15644" checked=checked onclick="set_default_address('15644')" id="default_billing_address">
												<div class="billing-address-list">
													<p>{{ item.address }}</p>
													<p>{{ item.city.name }}</p>
													<p>{{ item.state }}</p>
													<p>{{ item.zip }}</p>
													<a href="{% url 'address:update_billingaddress' item.pk %}" class="action action-editaddress" address-id="15644" user-address-id="15644"><span>Edit</span></a>
												</div>
												{% endfor %}
											</div>
										</div>
									</div>

									<small class="schedule-home-form" style="display:none">Add Your Billing Details</small>
										<form action="/checkout/add_billing_address" id="add_billing_address_form" class="schedule-home-form" style="display:none" method="post">
											<input type="hidden" name="csrf_test_name" value="26424dddac305e9f479f8c929363d4e2" />
											<input autocomplete="false" name="hidden" type="text" style="display:none;">
											<div class="form-group">
												<input type="hidden" name="id" id="address_id">
												<input type="hidden" name="address_id" id="user_address_id">
												<input type="text" name="address_1" id="address_1" class="form-control checkout-flow-input" placeholder="Address Line 1">
												<span class="form-error"></span>
											</div>
											<div class="form-group">
												<input type="text" name="address_2" id="address_2" class="form-control checkout-flow-input" placeholder="Address Line 2 (Optional)">
												<span class="form-error"></span>
											</div>
											<div class="form-row">
												<div class="form-group col-md-6 state">
													<input type="text" name="billing-state" id="billing-state" class="form-control checkout-flow-input" placeholder="Change State" autocomplete="off" value="Haryana" readonly />
													<input type="hidden" name="state_id" id="billing-state-holder" value="12" />
													<span class="form-error"></span>
												</div>
												<div class="form-group col-md-6 city">
													<input type="text" id="billing-city" class="form-control checkout-flow-input" placeholder="Change City" value="Gurugram" readonly />
													<input type="hidden" name="city_id" id="billing-city-holder" value="100" />
													<span class="form-error"></span>
												</div>
											</div>
											<div class="form-row">
												<div class="form-group col-md-6">
													<input type="text" name="pincode" id="pincode"class="form-control checkout-flow-input number_only" placeholder="Pin Code" maxlength="6">
													<span class="form-error"></span>
												</div>
											</div>
											<div class="form-group">
												<button type="submit" class="btn btn-1" id="add-billing-address-btn">Next</button>
											</div>
										</form>

									<div class="col-md-12 text-right">
										<div class="">
											<a class="action action-address" onclick="add_billing_address();">
												<img src="/assets/images/add.svg">
												<span>Add Address</span>
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>

</div>

{% endblock %}



{% block extra_jscript %}
<script type='text/javascript'>
$(document).ready(function()
{
});
</script>

{% endblock %}

templates/checkout/callback.html
{% extends 'base_shop.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block extra_style %}
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/style_shopdetail.css' %}" rel="stylesheet" type="text/css">
{% endblock %}


{% block content %}

<!-- Inner checkout items start -->
<div class="inner-checkout">
	<div class="container">

		<div class="row">
			<div class="col-lg-8 col-md-8 col-sm-12">
				<div class="flex-inline">

				{% if status == "Success" %}

				<h2>THANKS YOUR PAYMENT HAS BEEN RECEIVED</h2>
				{% else %}
				<h2>SORRY, YOUR PAYMENT HAS BEEN FAILED</h2>
				{% endif %}

				</div>
			</div>
		</div>

	</div>
</div>

{% endblock %}

templates/checkout/checkout.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block extra_style %}
{% endblock %}


{% block content %}

<!-- Inner checkout items start -->
<div class="inner-checkout">
	<div class="container">

		<div class="row">

			<div class="col-lg-8 col-md-8 col-sm-12">
				<div class="flex-inline">
					<div class="heading-small-v-2">Order Overview{{ total_payment.get_final_price }}</div>
					<a href="/book-test/" class="btn-1 btn">+ Add Tests</a>
				</div>

				<div class="accordian checkout-collapse">

					<!-- Sidebar patient add -->
					<!-- item-2 -->
					<div id="checkout-collapse-item-2">
						<div class="card">
							<div class="card-header" id="headingTwo">
								<h2 class="mb-0">
									<button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapse-item-2" id="billing_address" aria-expanded="false" aria-controls="collapse-item-2">1. Billing Address</button>
								</h2>
							</div>

							<style>
							.form-group .easy-autocomplete
							{
								width: 100%!important;
							}
							</style>

							<div id="collapse-item-2" class="collapse checkout-collapse-body" aria-labelledby="headingTwo" data-parent="#checkout-collapse-item-2">
								<div class="card-body">
									<div class="row billing-address">
										<div class="col-md-6">
											<div class="box">
												{% for item in user_address %}
												<input type="radio" name="default_address" data-address-id="15644" checked=checked onclick="set_default_address('15644')" id="default_billing_address">
												<div class="billing-address-list">
													<p>{{ item.address }}</p>
													<p>{{ item.city.name }}</p>
													<p>{{ item.state }}</p>
													<p>{{ item.zip }}</p>
													<a href="{% url 'address:update_billingaddress' item.id %}" class="action action-editaddress" address-id="{% url 'address:update_billingaddress' item.id %}" user-address-id="{% url 'address:update_billingaddress' item.id %}"><span>Edit</span></a>
												</div>
												{% endfor %}
											</div>
										</div>
									</div>

									<small class="schedule-home-form" style="display:none">Add Your Billing Details</small>
										<form action="/checkout/add_billing_address" id="add_billing_address_form" class="schedule-home-form" style="display:none" method="post">
											<input type="hidden" name="csrf_test_name" value="26424dddac305e9f479f8c929363d4e2" />
											<input autocomplete="false" name="hidden" type="text" style="display:none;">
											<div class="form-group">
												<input type="hidden" name="id" id="address_id">
												<input type="hidden" name="address_id" id="user_address_id">
												<input type="text" name="address_1" id="address_1" class="form-control checkout-flow-input" placeholder="Address Line 1">
												<span class="form-error"></span>
											</div>
											<div class="form-group">
												<input type="text" name="address_2" id="address_2" class="form-control checkout-flow-input" placeholder="Address Line 2 (Optional)">
												<span class="form-error"></span>
											</div>
											<div class="form-row">
												<div class="form-group col-md-6 state">
													<input type="text" name="billing-state" id="billing-state" class="form-control checkout-flow-input" placeholder="Change State" autocomplete="off" value="Haryana" readonly />
													<input type="hidden" name="state_id" id="billing-state-holder" value="12" />
													<span class="form-error"></span>
												</div>
												<div class="form-group col-md-6 city">
													<input type="text" id="billing-city" class="form-control checkout-flow-input" placeholder="Change City" value="Gurugram" readonly />
													<input type="hidden" name="city_id" id="billing-city-holder" value="100" />
													<span class="form-error"></span>
												</div>
											</div>
											<div class="form-row">
												<div class="form-group col-md-6">
													<input type="text" name="pincode" id="pincode"class="form-control checkout-flow-input number_only" placeholder="Pin Code" maxlength="6">
													<span class="form-error"></span>
												</div>
											</div>
											<div class="form-group">
												<button type="submit" class="btn btn-1" id="add-billing-address-btn">Next</button>
											</div>
										</form>

									<div class="col-md-12 text-right">
										<div class="">
											<a class="action action-address" href="{% url 'address:create_billingaddress' %}">
												<img src="/assets/images/add.svg">
												<span>Add Address</span>
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

					<!-- item-4 -->
					<div id="checkout-collapse-item-4" class="home-collection-date-and-time" style="display:none;">
						<div class="card">
							<div class="card-header" id="headingFour">
								<h2 class="mb-0">
									<button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapse-item-4" aria-expanded="false" aria-controls="collapse-item-4" id="home_collection_datetime_tab">4. Preferred Home Collection Date & Time</button>
								</h2>
							</div>

							<div id="collapse-item-4" class="collapse checkout-collapse-body" aria-labelledby="headingFour" data-parent="#checkout-collapse-item-4">
								<div class="card-body">
									<form action="/checkout/add_home_collection_other_details" id="home_collection_other_details_form" class="m-t-10" method="post">
										<input type="hidden" name="csrf_test_name" value="26424dddac305e9f479f8c929363d4e2" />
										<input type="hidden" name="is_home_collection" value="" />
										<input type="hidden" name="home_collection_other_detail_id" value="" />
										<div class="home-collection-other-details">
											<small class="m-b-10">Home Collection Date and Time</small>
											<div class="form-row">
												<div class="form-group col-md-6">
													<input type="date" name="collection_date" id="collection_date" class="form-control checkout-flow-input" placeholder="Date" value="">
													<span class="form-error"></span>
												</div>
												<div class="form-group col-md-6">
													<select name="collection_time" class="form-control checkout-flow-select" id="collection_time" placeholder="Select">
														<option value="" selected="selected">Select</option>
														<option value="9:00 am to 6:00 pm">9:00 am to 6:00 pm</option>
													</select>
													<!--<input type="time" name="collection_time" id="collection_time" class="form-control checkout-flow-input" placeholder="Time" value="">-->
													<span class="form-error"></span>
												</div>
											</div>
											<div class="form-group">
												<button type="submit" id="add_home_collection_other_details_btn" class="btn btn-1">Next</button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>

					<!-- item-5 -->
					<div id="checkout-collapse-item-5">

						<div class="card">
							<div class="card-header" id="headingFive">
								<h2 class="mb-0">
									<button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapse-item-5" aria-expanded="false" aria-controls="collapse-item-5" id="payment_details">2. Payment Details</button>
								</h2>
							</div>

							<div id="collapse-item-5" class="collapse checkout-collapse-body" aria-labelledby="headingFive" data-parent="#checkout-collapse-item-5">
								<div class="card-body">
									<form action="" id="add_payment_details_form" method="POST">
										{% csrf_token %}
										<small class="m-b-10">Select payment mode</small>
										<div class="form-group checkbox-group">
											<div class="inner-group">
												<label class="container-check" checked="checked">Online
													<input type="radio" name="payment_mode" value="Online">
													<span class="checkmark"></span>
												</label>
											</div>
											<div class="inner-group">
												<label class="container-check">Cash at home
													<input type="radio" name="payment_mode" value="Cash" checked="checked">
													<span class="checkmark"></span>
												</label>
											</div>
										</div>
										<span class="form-error"></span>
										<button type="submit" class="btn btn-1 m-12 add_payment_details_btn" id="add_payment_details_btn">Proceed to Book test</a>
									</form>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>

			<!-- Sidebar Summary -->
			<div class="col-lg-4 col-md-4 col-sm-12">
				<div class="checkout-summary">
					<div class="heading-small-v-2">Summary</div>
					<div class="row m-t-40">
						{% for item in products %}
						<div class="summary-item-name col-md-9" id="12261">{{ item.product.title }} </div>
						<div class="summary-item-price col-md-3">&#8377; {{ item.product.price }}</div>
						<div class="summary-patient-name col-md-12">Patient : </div>
						{% endfor %}
					</div>

					{% if cart_order.get_total_price %}
					<div class="flex-inline border" style="border-left: 0px!important; border-right: 0px!important; border-bottom: 0px!important; padding: 10px 0; margin-bottom: 15px;">
						<p>Subtotal</p>
						<p class="subtotal">&#8377; {{ cart_order.get_total_price }}</p>
					</div>

					<div class="flex-inline home-collection-charges" style="display:none">
						<p class="text-right"><span style="display: inline-block; float:left;"> Home Collection charge </span> &#8377;
							<!-- <span id="collection-charges" style="float:right;">0</span> -->
							<span id="collection-charges" style="float:right;">0</span>
						</p>
					</div>
					<div class="flex-inline border strong-summary-text">
						<p>Total</p>
						<p class="total-charges">&#8377; {{ cart_order.get_total_price }}</p>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>

</div>

{% endblock %}



{% block extra_jscript %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script type='text/javascript'>
$(document).ready(function()
{
    var options =
    {
    	key: "{{ razorpay_key }}",
    	amount: "{{ amount }}",
    	currency: "{{ currency }}",
    	name: "{{ store_name }}",
    	image: "http://127.0.0.1:8000/assets/images/shrinivasdiagnostics_logo.png",
    	order_id: "{{ provider_order_id }}",
    	callback_url: "{{ callback_url }}",
    	redirect: true,
    	prefill: {
    		"name": "{{ full_name }}",
    		"email": "{{ email }}",
    		"contact": "{{ phone_number }}"
    	},
    	notes: {
    		"address": "ShrinivasDiagnostic Lab Office"
    	},
    	theme: {
    		"color": "#528FF0"
    	}
    };

	var amount = "{{ cart_order.get_total_price }}";
	amount = parseInt(amount, 0);

	$('input:radio[name="payment_mode"]').click(function(e)
	{
		var payment_mode = $(this).val();

		if ($(this).is(':checked') && $(this).val() == 'Online')
		{
			console.log("amount", amount);
			console.log("amount", typeof(amount));
			// e.preventDefault();
		}
		else
		{
			// console.log("payment_mode", payment_mode);
		}

		$.ajax(
		{
			url: "/checkout/",
			type: "POST",
			dataType: "json",
			data:
			{
				csrfmiddlewaretoken: '{{ csrf_token }}',
				payment_mode: payment_mode,
				amount: amount,
			},
			success : function(json)
			{
				// alert("Successfully sent the URL to Django");
			},
			error : function(xhr,errmsg,err)
			{
				// alert("Could not send URL to Django. Error: " + xhr.status + ": " + xhr.responseText);
			}
		});

	})
});
</script>

{% endblock %}

templates/checkout/payment.html
{% block head_title %}
{{ page_title }}
{% endblock %}

{% block content %}
<form method="POST">
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
    var options =
    {
    	key: "{{ razorpay_key }}",
    	amount: "{{ amount }}",
    	currency: "{{ currency }}",
    	name: "{{ store_name }}",
    	image: "http://127.0.0.1:8000/assets/images/shrinivasdiagnostics_logo.png",
    	order_id: "{{ provider_order_id }}",
    	callback_url: "{{ callback_url }}",
    	redirect: true,
    	prefill: {
    		"name": "{{ full_name }}",
    		"email": "{{ email }}",
    		"contact": "{{ phone_number }}"
    	},
    	notes: {
    		"address": "ShrinivasDiagnostic Lab Office"
    	},
    	theme: {
    		"color": "#528FF0"
    	}
    };

    var rzp1 = new Razorpay(options);
    rzp1.open();
	</script>
</form>

{% endblock %}

templates/checkout/thanks_cash.html
{% extends 'base_shop.html' %}

{% load static %}
{% load i18n %}

{% block head_title %}
{{ product.name }}
{% endblock %}

{% block extra_style %}
<link href="{% static 'css/style_search.css' %}" rel="stylesheet" type="text/css">
<style>
input#search-bar-header:focus::-webkit-input-placeholder {
transition: opacity 0.45s ease;
opacity: 0;
}

input#search-bar-header:focus::-moz-placeholder {
transition: opacity 0.45s ease;
opacity: 0;
}

input#search-bar-header:focus:-ms-placeholder {
transition: opacity 0.45s ease;
opacity: 0;
}

div,
.profile-item {
word-wrap: break-word;
}
</style>
{% endblock %}

{% block content %}

<!-- Inner checkout items start -->
<div class="inner-checkout">
  <div class="container">

    <div class="row">
      Thanks
    </div>
  </div>
</div>


{% endblock %}

<script src="{% static 'js/jquery-3.6.0.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/select2.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/site.js' %}" type="text/javascript"></script>
<script src="{% static 'js/toastr.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.flexslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.easy-autocomplete.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/sweetalert2.min.js' %}" type="text/javascript"></script>

{% block extra_jscript %}
{% endblock %}

templates/checkout/update_address.html
{% extends 'base_shop.html' %}

{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block head_title %}
{{ page_title }}
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block extra_style %}
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'css/style_shopdetail.css' %}" rel="stylesheet" type="text/css">
{% endblock %}


{% block content %}

<!-- Inner checkout items start -->
<div class="inner-checkout">
	<div class="container">

		<div class="row">

			<div class="col-lg-8 col-md-8 col-sm-12">
				<div class="flex-inline">
					<div class="heading-small-v-2">Billing Address{{ total_payment.get_final_price }}</div>
					<a href="/book-test/" class="btn-1 btn">+ Add Tests</a>
				</div>

				<div class="accordian checkout-collapse">
					<small class="schedule-home-form" style="display:none">Add Your Billing Details</small>
						<form action="{% url 'order:checkout' %}" id="add_billing_address_form" class="schedule-home-form" method="POST">
						{% csrf_token %}
							{{ form|crispy }}
							<div class="form-group">
								<button type="submit" class="btn btn-1" id="add-billing-address-btn">Save</button>
							</div>
						</form>

					</div>
				</div>
			</div>

		</div>
	</div>

</div>

{% endblock %}



{% block extra_jscript %}
<script type='text/javascript'>
$(document).ready(function()
{
});
</script>

{% endblock %}